const category = [
    'Fast food restaurant',
    'Family restaurant',
    'South Indian restaurant',
    'Food court',
    'Marathi restaurant',
    'Barbecue restaurant',
    'Bakery',
    'North Indian restaurant',
    'Indian restaurant',
    'Bar & grill',
    'Mughlai restaurant',
    'Non vegetarian restaurant',
    'Pizza restaurant',
    'Vegetarian restaurant',
    'Rajasthani restaurant',
    'Breakfast restaurant',
    'Italian restaurant',
    'Punjabi restaurant',
    'Candy store',
    'Chicken restaurant',
    'Fine dining restaurant',
    'Biryani restaurant',
    'Sandwich shop',
    'Middle Eastern restaurant',
    'Takeout restaurant',
    'Small plates restaurant',
    'American restaurant',
    'Chinese restaurant',
    'Dhaba',
    'Juice shop',
    'Grill',
    'Shawarma restaurant',
    'Bar',
    'Momo restaurant',
    'Asian restaurant',
    'Buffet restaurant',
    'Bengali restaurant',
    'Country food restaurant',
    'Hyderabadi restaurant',
    'Seafood restaurant',
    'Dessert shop',
    'Health food restaurant',
    'Vegan restaurant',
    'Ice cream shop',
    'Hamburger restaurant',
    'Diner',
    'Seafood donburi restaurant',
    'Gujarati restaurant',
    'Snack bar',
    'Indian takeaway',
    'Fish & chips restaurant',
    'Hoagie restaurant',
    'Cold noodle restaurant',
    'Cape Verdean restaurant',
    'Afghan restaurant',
    'Tiffin center',
    'Continental restaurant',
    'Mandarin restaurant',
    'Chinese noodle restaurant',
    'Fondue restaurant',
    'Sundae restaurant',
    'Fish restaurant',
    'Rice restaurant',
    'Korean restaurant'
]


export default category;