const category = [
    'Afghan restaurant',
    'American restaurant',
    'Asian restaurant',
    'Bakery',
    'Bar',
    'Bar & grill',
    'Barbecue restaurant',
    'Bengali restaurant',
    'Biryani restaurant',
    'Buffet restaurant',
    'Candy store',
    'Cape Verdean restaurant',
    'Chicken restaurant',
    'Chinese noodle restaurant',
    'Chinese restaurant',
    'Cold noodle restaurant',
    'Continental restaurant',
    'Country food restaurant',
    'Dessert shop',
    'Dhaba',
    'Diner',
    'Fast food restaurant',
    'Family restaurant',
    'Fine dining restaurant',
    'Fish & chips restaurant',
    'Fish restaurant',
    'Food court',
    'Fondue restaurant',
    'Gujarati restaurant',
    'Grill',
    'Health food restaurant',
    'Hamburger restaurant',
    'Hoagie restaurant',
    'Hyderabadi restaurant',
    'Ice cream shop',
    'Indian restaurant',
    'Indian takeaway',
    'Italian restaurant',
    'Juice shop',
    'Korean restaurant',
    'Mandarin restaurant',
    'Marathi restaurant',
    'Middle Eastern restaurant',
    'Momo restaurant',
    'Mughlai restaurant',
    'Non vegetarian restaurant',
    'North Indian restaurant',
    'Pizza restaurant',
    'Punjabi restaurant',
    'Rajasthani restaurant',
    'Rice restaurant',
    'Sandwich shop',
    'Seafood donburi restaurant',
    'Seafood restaurant',
    'Small plates restaurant',
    'Snack bar',
    'South Indian restaurant',
    'Sundae restaurant',
    'Takeout restaurant',
    'Tiffin center',
    'Vegan restaurant',
    'Vegetarian restaurant'
]


export default category;